### ISSUE TITLE
Deleting lead_gas cruncher

### ISSUE THREAD

**Issue by Rlamboll** [znicholls/silicone#50]
Currently I don't see a use-case for the lead gas scenario. It seems very unlikely that we'd have data for exactly one timestep for the follow gas - normally we have either no or most times. The constant_ratio cruncher does the same job but with more freedom to work in cases where we have more than one timestep. 

**Describe the solution you'd like**

Delete the cruncher and all uses of it to compactify the code. 

**Describe alternatives you've considered**

Do nothing

**Comment by znicholls** [comment]
> It seems very unlikely that we'd have data for exactly one timestep for the follow gas - normally we have either no or most times.

It is a rare use case, but one I had to deal with last year so would prefer to keep the functionality somewhere. However, it would probably make more sense if we refactored it so that it used `DatabaseCruncherConstantRatio` under the hood (see suggestion below). 

To explain the use case, we had a bunch of gases for which we had historical emissions estimates but no projections. So what we wanted to do was take our historical emissions point (say 2015 emissions) and then simply project it forward following the path from some other emissions timeseries. You could do this with `DatabaseCruncherConstantRatio` if you did the following two steps:

1. work out the ratio between the follower gas and the lead gas in 2015
1. Use `DatabaseCruncherConstantRatio` to infill

**Comment by Rlamboll** [comment]
Ok, I'll leave this on the to-do list to compactify, but won't delete the functionality.

**Comment by Rlamboll** [comment]
This cruncher will be made more useful by #52 which allows the infiller to use the latest data in the case of multiple dates and to take averages in the case of multiple scenarios.
